---
# handlers file for worker
- name: Restart SSH service
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Restart containerd service
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Restart kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
