apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
# Use solo address
#  - <ip-address>/32
# Use range
#  - <first-ip>-<last-ip>

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
